### PR TITLE
Add line drawing using Unicode line drawing characters as an option

### PR DESCRIPTION
**Pull request by pjsg**
This pull request does the following:
- Fixes the package metadata so that it points to the correct repository
- Add support to calculate character widths using unicode rules
- Adds an option to draw the boxes using the unicode line drawing characters.
- Adds unit tests for the above.
- Updated the documentation and increased the version number.

The first two items above are actually from other forks of this repo, and seem useful.

Thanks

### CODE REVIEW

**Comment by marcusramberg** [comment]
Hey Philip. 

Seems I missed this PR like 3 years ago. Sorry about that. If you make it apply cleanly to master I'd be happy to accept it.

**Comment by pjsg** [comment]
Fixed -- I just removed the update to the metadata as you had merged another PR with a similar change.

**Comment by marcusramberg** [comment]
Thanks! :)

**Comment by stesachse** [comment]
this breaks `make test` if none of `Unicode::GCString`, `Text::VisualWidth::UTF8` or `Text::VisualWidth::PP` is installed. `t/05tables_cjk.t` always fails because the text is not wrapped. btw: i don't know how to add a dependency to one random module out of 3 possible

**Pull request merged**
